# Implement an Ansible playbook to create a new virtual machine in Azure with basic configuration
# Create a new resource group, a new virtual network, a new subnet, a new public IP address, a new network interface, and a new virtual machine with basic configuration
# The playbook should be idempotent, meaning that it should not fail if the resource group, virtual network, subnet, public IP address, network interface, and virtual machine already exist
#variables
- name: Define the variables needed to create the resources
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group: "demoPayRetailers-rg-ansible"
    location: "westeurope"
    vnet_name: "demoPayRetailers-vnet-ansible"
    vnet_address_prefix: "10.0.0.0/16"
    subnet_name: "demoPayRetailers-subnet-ansible"
    subnet_address_prefix: "10.0.0.0/24"
    public_ip_name: "demoPayRetailers-pip-ansible"
    nic_name: "demoPayRetailers-nic-ansible"
    vm_name: "demoPayRetailers-vm-ansible"
    vm_size: "Standard_B1s"
    admin_username: "Sara"
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCjpHB0CiCd+h6YhQt2C87OH5KwVRtpcRO/fiIPXTUKStLkv0zFCTbnHGXcn/Dw5SB7/z0A0LqqKLlAM5aNgsUKHcVdlJOwHXWr9ghnlQcjeWX4GwxN0bq6WydTNT0QXLIua5f/HNPNkzUZLEm2N/yt26owN3EVcKEKnIOKCTr6Pn3qeF2SUHMVG0HV/Ge5lQ+6lTm6Mi+vOZ2TIfOaIk+fXwvfmOkAr43S7xlnlns0FbuNzr+Ug9zhBXI37kB93UnEdY7xWqhyMvoPEliwpyKAnDH0NuTHWocI/7m6rWWWx1TMZVTLmF8ltou65+BoSa1J2eSDJPEih5NhH7g8UKyezX7IYIxMgySQsi9tN6W3j/YtTNFMv2hLdStt6VLjGho56J5b+FLZ9Gj/6H4TZ/17Zmb9yagmy9YQRtWuY8w83VPgR7H3fCLLXsT0Xpw0F5DZUxs8wIdWOKKjfl1zQRhEUAkvpEZFttjzICpku0Y8dH56803gcEzk6UknGB6BtZM/JkDVnoe2n2LKwDW/fzhMSa8i4CF3POQs8IbuldIuGp9smjRvQCd25rd6HS3Ph/sAl4xr9n1T6Q7NAWAfpFwMnKgdaNpEfSMDEfgqQiL45YAcZhHrGMwqBLEsZl9pk6d2mhYscstU6bbSUvsq+LLjNLH+IO8XMPm17T2ijTa6LQ== sara@DESKTOP-SGE6CIV"
    image_offer: "UbuntuServer"
    image_publisher: "Canonical"
    image_sku: "18.04-LTS"
    image_version: "latest"
  tasks:
  - name: Create a new resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create a new virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vnet_name }}"
      address_prefixes_cidr:
      - "{{ vnet_address_prefix }}"
  - name: Create a new subnet

    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      virtual_network_name: "{{ vnet_name }}"
      name: "{{ subnet_name }}"
      address_prefix_cidr: "{{ subnet_address_prefix }}"

  - name: Create a new public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip_name }}"

  - name: Create a new network interface
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      virtual_network_name: "{{ vnet_name }}"
      subnet_name: "{{ subnet_name }}"
      public_ip_name: "{{ public_ip_name }}"
      name: "{{ nic_name }}"

  - name: Create a new virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_size }}"
    admin_username: "{{ admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
    - path: /home/{{ admin_username }}/.ssh/authorized_keys
      key_data: "{{ ssh_public_key }}"
    network_interfaces:
    - name: "{{ nic_name }}"
    image:
      offer: "{{ image_offer }}"
      publisher: "{{ image_publisher }}"
      sku: "{{ image_sku }}"
      version: "{{ image_version }}"
    os_disk:
      name: "{{ vm_name }}-osdisk"
      caching: ReadWrite
      create_option: FromImage
    os_type: Linux
    state: present

        




