# Implement an Ansible playbook to create a new virtual machine in Azure with basic configuration
# Create a new resource group, a new virtual network, a new subnet, a new public IP address, a new network interface, and a new virtual machine
# The playbook should be idempotent, meaning that it should not fail if the resource group, virtual network, subnet, public IP address, network interface, and virtual machine already exist
#variables
- name: Define the variables needed to create the resources
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group: "test-IaC-Ansible-GitHubActions"
    location: "westeurope"
    vnet_name: "test-IaC-Ansible-GitHubActions"
    vnet_address_prefix: "10.0.0.0/16"
    subnet_name: "test-IaC-Ansible-GitHubActions"
    subnet_address_prefix: "10.0.0.0/24"
    public_ip_name: "test-IaC-Ansible-GitHubActions"
    nic_name: "test-IaC-Ansible-GitHubActions"
    vm_name: "test-IaC-Ansible-GitHubActions"
    vm_size: "Standard_B1s"
    admin_username: "Sara"
    admin_password: "P@ssw0rd1234"
    image_offer: "UbuntuServer"
    image_publisher: "Canonical"
    image_sku: "18.04-LTS"
    image_version: "latest"

#tasks
- name: Create a new resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
  register: rg

- name: Create a new virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ vnet_address_prefix }}"
  register: vnet

- name: Create a new subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    virtual_network_name: "{{ vnet_name }}"
    name: "{{ subnet_name }}"
    address_prefix: "{{ subnet_address_prefix }}"
  register: subnet

- name: Create a new public IP address
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: "{{ public_ip_name }}"
  register: public_ip

- name: Create a new network interface
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    virtual_network_name: "{{ vnet_name }}"
    subnet_name: "{{ subnet_name }}"
    public_ip_name: "{{ public_ip_name }}"
    name: "{{ nic_name }}"
  register: nic

- name: Create a new virtual machine
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_size }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    image:
      offer: "{{ image_offer }}"
      publisher: "{{ image_publisher }}"
      sku: "{{ image_sku }}"
      version: "{{ image_version }}"
    network_interfaces: "{{ nic.id }}"
  register: vm
  
  