# - name: Test Ansible connection
#   hosts: localhost
#   gather_facts: false

#   tasks:
#     - name: Print a message
#       debug:
#         msg: "Ansible is working correctly!"


# Create and ansible playbook to deploy an Azure Storage Account. Install all the required modules and run the playbook.
# Make sure you have the required modules installed. 
# Make sure you are using the correct module to deploy the storage account.

- name: Create a resource group
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansible-rg
        location: eastus
        tags:
          environment: test
          department: it
          project: ansible
      register: rg

- name: Create a storage account
  hosts: localhost
  connection: local
  tasks:
    - name: Create storage account
      azure_rm_storageaccount:
        resource_group: ansible-rg
        name: ansiblestorageaccount
        account_type: Standard_LRS
        location: eastus
        tags:
          environment: test
          department: it
          project: ansible
      register: sa

- name: Create a storage container
  hosts: localhost
  connection: local
  tasks:
    - name: Create storage container
      azure_rm_storagecontainer:
        resource_group: ansible-rg
        storage_account_name: ansiblestorageaccount
        name: ansiblestoragecontainer
        container_access_type: private
        state: present
        tags:
          environment: test
          department: it
          project: ansible
      register: sc




